### ISSUE TITLE
add rules for no paragraph indent after sections or content breaks

### ISSUE THREAD

**Issue by kamorrissey** [FriendsOfEpub/Blitz#16]
It is a typographic tradition from print books that there should be no paragraph ident after a section heading or content break. This looks attractive and is just as meaningful in ebooks. I propose it be added (at least as an option) to Blitz (and, perhaps, be added to ebook tricks). The basic CSS is as follows:

```
h1 + p,
h2 + p,
h3 + p,
h4 + p,
h5 + p,
h6 + p,
hr + p {
    text-indent: 0;
}
```

I'm not sure how to handle cases where there is content between a `<h1>` and first `<p>` tag, such as an epigram.

**Comment by JayPanoz** [comment]
Hmm, let me think about the best way to implement that.

It should probably be an option since it’s more of a stylistic choice in some languages (so that would be a namespace in LESS) and I’ve been willing to internationalize Blitz for some time now…

I can see how to handle some cases where there is content between a heading and the first paragraph but I must check whether edge cases exist. 

Thanks for pointing that out, appreciated.

**Comment by JayPanoz** [comment]
@kamorrissey 

Will such “typesetting packages” do? https://github.com/FriendsOfEpub/Blitz/commit/9f2d35c91a801440d58efb1ab9e33d03e9ecc0b8 

They’re disabled by default e.g. you must add `#non-indented-first-para` to output it. 

It comes at a high cost though as we don’t have context (cf. selector) and I’m wondering if this shouldn’t simply be the author’s call i.e. she/he add this declaration in the publication-context.

**Comment by lumpynose** [comment]
Jay, a clever way (hack) to do this is to set the text-indent to 0 for the p tag, and then have a css rule "p+p" and set its text-indent to 1em (or whatever).  So the p+p says that whenever there's a paragraph _after_ a paragraph, indent it, and the otherwise case, no indent.  Seems sort of backwards having no indent on the p tag, but it works with minimal tagging in the html.

**Comment by JayPanoz** [comment]
Given the Blitz project is under an “End of Life process”, this issue has been frozen, labeled `wontfix`, and won’t be addressed any further. Please check #66 for more details.
