### ISSUE TITLE
small-caps text-tranform

### ISSUE THREAD

**Issue by pkra** [FriendsOfEpub/Blitz#28]
I noticed https://github.com/FriendsOfEpub/Blitz/blob/88ccb26627dc003dc037a97cea6407dd0117081d/Blitz_framework/LESS/utils/utilities.less#L272 the other day.

This reset seems unexpected to me. Is there a technical reason for this?

**Comment by JayPanoz** [comment]
That’s an interesting question because it would make more sense to have this util as `.caps-to-small-caps`, and I can’t recall why it’s just `.small-caps`… 

But I’m suspecting a bias towards French typography.

The typical use case for French would probably be centuries e.g. `<span class="small-caps">XX</span><sup>e</sup> siècle`. So in ADE, it means this falls backs on caps for the roman numeral – which is a lot better than “xxe siècle.”

That said, it should not be that much specific to a particular use-case. `.small-caps` and `.caps-to-small-caps` would even map to OTF a lot better actually. I’ll try updating ASAP. 

Thanks for the report!

**Comment by pkra** [comment]
Ah that makes sense. Thanks for fixing it so rapidly!

Side question: why the `font-size: small;` in mobi7?

**Comment by JayPanoz** [comment]
Ah you’re right, rolled out a patch for this. Only `.caps-to-small-caps` should have `font-size: small` then, to “mimic” smaller capitals. Thanks again.

**Comment by pkra** [comment]
Thanks, Jiminy!
