### ISSUE TITLE
Cropped numbers in lists on iPhone

### ISSUE THREAD

**Issue by momoha2** [FriendsOfEpub/Blitz#40]
One of our client has just reported to me that numbers in ordered lists on iBooks on iPhone were cropped. To solve the problem, I had to remove the reset and parameters of <ol>: 

ol,
margin: 0;
padding: 0;

ol {
  margin: 1.5em 0;
  padding-left: 5%;
}

I’m not sure if the problem could come from my client’s phone/iBooks not being updated or something, or if it is a genuine problem of Blitz. I would be happy to get an answer about it though :-) Thanks!

**Comment by JayPanoz** [comment]
That’s most probably an issue with the default value on narrower/smaller screens. I’ve just checked a bigger font-size in a square-ish context, and you can see numbers are already overflowing a little bit because those markers are kinda “floating” out of the `padding-left`: 

![Capture d’écran 2019-10-15 à 18 29 43](https://user-images.githubusercontent.com/12599652/66850940-0cb8d880-ef7a-11e9-975e-dd627644539b.png)

This appears to be consistent with web rendering so I’m even wondering whether other apps are adding some sort of extra margin to protect against that. Anyways, it slipped through the cracks so I’ll try to fix this issue ASAP. 

I don’t necessarily like the idea of using relative units for that (e.g. `em`) as the `padding-left` will increase with `font-size` but on the other hand, the number size will increase with font-size so I don’t really imagine there’s another option available. 

Indeed their `padding-left` is the `40px` HTML5 suggested rendering default, and this can happen in the largest `font-sizes` anyway so even absolute units won’t resolve this issue.

Capture below is using their default:

![Capture d’écran 2019-10-15 à 18 46 06](https://user-images.githubusercontent.com/12599652/66851968-41c62a80-ef7c-11e9-80b6-3c1cccfa2a4e.png)

**Comment by JayPanoz** [comment]
So I made this change to the default: 

https://github.com/FriendsOfEpub/Blitz/blob/22e513a12dc3fceae4c71d1d7b0cbb799217c554/Blitz_framework/CSS/blitz.css#L457-L474

This will now be using the base font-size, multiply by 2 for lists (then use base `font-size` for nested lists). 

If no one voices their disagreement, will merge later this week.

**Comment by JayPanoz** [comment]
This change has been merged. Thanks again for the bug report.
